version: "3.0"

services:
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/

  course_app:
    image: riadesigner/course-app:v-0.0.1      
    restart: always
    working_dir: /app
    ports:
      - 8000:5000
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://root:pass@mongo:27017/    
    depends_on:
      - mongo
